### ISSUE TITLE
error with readme's auto-generated TOC

### ISSUE THREAD

**Issue by ghost** [Tixit/Gem.js#14]
```md
- [Instance properties inherited from [`EventEmitter`](http://nodejs.org/api/events.html)](#instance-properties-inherited-from-eventemitterhttpnodejsorgapieventshtml)
```

does not render correctly and comes out as 

- [Instance properties inherited from [`EventEmitter`](http://nodejs.org/api/events.html)](#instance-properties-inherited-from-eventemitterhttpnodejsorgapieventshtml)

the `#instance-properties-inherited-from-eventemitterhttpnodejsorgapieventshtml` anchor is also invalid.

**Comment by fresheneesz** [comment]
Ok fixed! Thanks for the report!
